ALTER TABLE orders
ADD COLUMN payment_method VARCHAR(50) NOT NULL DEFAULT 'efectivo',
ADD COLUMN notes TEXT DEFAULT '',
ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN is_voided BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN voided_at TIMESTAMP,
ADD COLUMN void_reason TEXT;
